title: Absurdle
author: Kevin Lin
description: Implementing an adversarial version of Wordle using sets and maps.
baseurl: "/absurdle"
url: "https://kevinl.info"
permalink: pretty

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile

github:
  private: false
  source:
    branch: "main"
    path: "/"
  repository_url: "https://github.com/kevinlin1/absurdle"
